PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Beer(
beername VARCHAR(40) PRIMARY KEY NOT NULL,
stylename VARCHAR(40),
brewername VARCHAR(40),
rating DECIMAL(2, 1),
pictureurl VARCHAR(200)
);
CREATE TABLE ItemListing(
beername VARCHAR(40) PRIMARY KEY NOT NULL,
number INTEGER PRIMARY KEY NOT NULL,
store VARCHAR(16) PRIMARY KEY NOT NULL,
price DECIMAL(5,2),
size REAL PRIMARY KEY NOT NULL
);
CREATE TABLE Rating(
email VARCHAR(40) PRIMARY KEY NOT NULL,
beername VARCHAR(40) PRIMARY KEY NOT NULL,
rating INTEGER,
bestvalue DOUBLE PRECISION
);
CREATE TABLE User(
email CHAR(40) PRIMARY KEY NOT NULL,
password CHAR(15)
);
COMMIT;
